#@ load("@ytt:data", "data")
---

apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.GITOPS_SSH_SECRET_NAME
  annotations:
    tekton.dev/git-0: #@ data.values.URL
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.USERNAME
  password: #@ data.values.PASSWORD