#@ load("@ytt:data", "data")
---

profile: #@ data.values.PROFILE

shared:
  ingress_domain: #@ data.values.INGRESS_DOMAIN
  image_registry:
    project_path: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
    username: #@ data.values.INTERNAL_REGISTRY_USERNAME
    password: #@ data.values.INTERNAL_REGISTRY_PASSWORD
  kubernetes_version: #@ data.values.KUBERNETES_VERSION
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $INTERNAL_REGISTRY_CA_CERT_PATH)

ceip_policy_disclosed: TRUE

buildservice:
  kp_default_repository: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_PROJECT + "/" + data.values.INTERNAL_REPOSITORY
  kp_default_repository_username: #@ data.values.INTERNAL_REGISTRY_USERNAME
  kp_default_repository_password: #@ data.values.INTERNAL_REGISTRY_PASSWORD

cartographer:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $INTERNAL_REGISTRY_CA_CERT_PATH)

supply_chain: #@ data.values.SUPPLY_CHAIN

#@ if data.values.SUPPLY_CHAIN == "basic":
ootb_supply_chain_basic:
  registry:
    server: #@ data.values.INTERNAL_REGISTRY_HOST
    repository: #@ data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
  gitops:
    ssh_secret: #@ data.values.GITOPS_SSH_SECRET_NAME
#@ elif data.values.SUPPLY_CHAIN == "testing":
ootb_supply_chain_testing:
  registry:
    server: #@ data.values.INTERNAL_REGISTRY_HOST
    repository: #@ data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
  gitops:
    ssh_secret: #@ data.values.GITOPS_SSH_SECRET_NAME
#@ elif data.values.SUPPLY_CHAIN == "testing_scanning":
ootb_supply_chain_testing_scanning:
  registry:
    server: #@ data.values.INTERNAL_REGISTRY_HOST
    repository: #@ data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
  gitops:
    ssh_secret: #@ data.values.GITOPS_SSH_SECRET_NAME
#@ end

tap_gui:
  metadataStoreAutoconfiguration: true
  app_config:
    auth:
      allowGuestAccess: true
    catalog:
      locations:
        - type: url
          target: #@ data.values.CATALOG_URL

metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP

scanning:
  metadataStore:
    url: ""

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  ingress:
    include: true
    enable_tls: false
  samples:
    include: true

appliveview:
  ingressEnabled: true

appliveview_connector:
  backend:
    ingressEnabled: true
    sslDeactivated: false

source_controller:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $INTERNAL_REGISTRY_CA_CERT_PATH)

namespace_provisioner:
  controller: true
  import_data_values_secrets:
  - name: #@ data.values.REGISTRY_SECRET_NAME
    namespace: #@ data.values.INSTALL_NAMESPACE
    create_export: true
