#@ load("@ytt:data", "data")
---
shared:
  ingress_domain: #@ data.values.INGRESS_DOMAIN
  image_registry:
    project_path: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_REGISTRY_SUPPLY_CHAIN_PROJECT
    secret:
      name: #@ data.values.REGISTRY_SECRET_NAME
      namespace: #@ data.values.INSTALL_NAMESPACE
  kubernetes_version: #@ data.values.KUBERNETES_VERSION
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $TAP_INTERNAL_REGISTRY_CA_CERT_PATH)

ceip_policy_disclosed: TRUE

profile: #@ data.values.PROFILE

supply_chain: #@ data.values.DEFAULT_SUPPLY_CHAIN

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.INTERNAL_REGISTRY_HOST
    repository: #@ data.values.INTERNAL_REGISTRY_SUPPLY_CHAIN_PROJECT
  gitops:
    ssh_secret: #@ data.values.GITOPS_SSH_SECRET_NAME

contour:
  envoy:
    service:
      type: LoadBalancer

buildservice:
  kp_default_repository: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_REGISTRY_PROJECT + "/" + data.values.INTERNAL_REGISTRY_TAP_PACKAGES_REPOSITORY
  kp_default_repository_secret:
    name: #@ data.values.REGISTRY_SECRET_NAME
    namespace: #@ data.values.INSTALL_NAMESPACE
  #@ if data.values.PROFILE == "full":
  exclude_dependencies: true
  #@ end

tap_gui:
  metadataStoreAutoconfiguration: true
  app_config:
    auth:
      allowGuestAccess: true
    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
    catalog:
      locations:
        - type: url
          target: #@ data.values.CATALOG_URL
    techdocs:
      builder:  #@ data.values.TECH_DOC_BUILDER
      publisher:
        type: #@ data.values.TECH_DOC_PUBLISHER_TYPE
        awsS3:
          bucketName: #@ data.values.TECH_DOC_PUBLISHER_BUCKET
          credentials:
            accessKeyId: #@ data.values.TECH_DOC_PUBLISHER_USERNAME
            secretAccessKey: #@ data.values.TECH_DOC_PUBLISHER_PASSWORD
          s3ForcePathStyle: true
          endpoint: #@ data.values.TECH_DOC_PUBLISHER_ENDPOINT
          region: #@ data.values.TECH_DOC_PUBLISHER_REGION

metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP

accelerator:
  ingress:
    include: true
    enable_tls: false
  samples:
    include: true

appliveview:
  ingressEnabled: true

appliveview_connector:
  backend:
    ingressEnabled: true
    sslDeactivated: false

namespace_provisioner:
  controller: true
  import_data_values_secrets:
  - name: #@ data.values.GITOPS_SSH_SECRET_NAME
    namespace: #@ data.values.INSTALL_NAMESPACE
    create_export: true

cartographer:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $TAP_INTERNAL_REGISTRY_CA_CERT_PATH)

source_controller:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $TAP_INTERNAL_REGISTRY_CA_CERT_PATH)

grype:
  namespace: #@ data.values.DEV_NAMESPACE
  targetImagePullSecret: #@ data.values.REGISTRY_SECRET_NAME
