#@ load("@ytt:data", "data")
---
shared:
  ingress_domain: #@ data.values.INGRESS_DOMAIN
  image_registry:
    project_path: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
    secret:
      name: #@ data.values.REGISTRY_SECRET_NAME
      namespace: #@ data.values.INSTALL_NAMESPACE
  kubernetes_version: #@ data.values.KUBERNETES_VERSION
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $INTERNAL_REGISTRY_CA_CERT_PATH)

ceip_policy_disclosed: TRUE

profile: #@ data.values.PROFILE

supply_chain: #@ data.values.SUPPLY_CHAIN

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.INTERNAL_REGISTRY_HOST
    repository: #@ data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
  gitops:
    ssh_secret: #@ data.values.GITOPS_SSH_SECRET_NAME

contour:
  envoy:
    service:
      type: LoadBalancer

buildservice:
  kp_default_repository: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_PROJECT + "/" + data.values.INTERNAL_REPOSITORY
  kp_default_repository_secret:
    name: #@ data.values.REGISTRY_SECRET_NAME
    namespace: #@ data.values.INSTALL_NAMESPACE
  #@ if data.values.PROFILE == "full":
  exclude_dependencies: true
  #@ end

tap_gui:
  metadataStoreAutoconfiguration: true
  app_config:
    auth:
      allowGuestAccess: true
    catalog:
      locations:
        - type: url
          target: #@ data.values.CATALOG_URL
    techdocs:
      builder: 'external'
      publisher:
        type: 'awsS3'
        awsS3:
          bucketName: techdocs
          credentials:
            accessKeyId: JWQ3rWfMBSbBMtDvomKP
            secretAccessKey: pJvhrfAsIOUxEclbzhC0joD7bDnFgtcH
          s3ForcePathStyle: true
          endpoint: http://minio.lab.int:9000

metadata_store:
  ns_for_export_app_cert: "*"

accelerator:
  ingress:
    include: true
    enable_tls: false
  samples:
    include: true

appliveview:
  ingressEnabled: true

appliveview_connector:
  backend:
    ingressEnabled: true
    sslDeactivated: false

namespace_provisioner:
  controller: true
  import_data_values_secrets:
  - name: #@ data.values.GITOPS_SSH_SECRET_NAME
    namespace: #@ data.values.INSTALL_NAMESPACE
    create_export: true

cartographer:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $INTERNAL_REGISTRY_CA_CERT_PATH)

source_controller:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $INTERNAL_REGISTRY_CA_CERT_PATH)

