#@ load("@ytt:data", "data")
---

profile: #@ data.values.PROFILE

ceip_policy_disclosed: true

buildservice:
  kp_default_repository: #@ data.values.HARBOR_REGISTRY_HOST + "/" + data.values.HARBOR_PROJECT + "/" + data.values.HARBOR_REPOSITORY
  kp_default_repository_username: #@ data.values.HARBOR_REGISTRY_USERNAME
  kp_default_repository_password: #@ data.values.HARBOR_REGISTRY_PASSWORD
  tanzunet_username: #@ data.values.TANZU_REGISTRY_USERNAME
  tanzunet_password: #@ data.values.TANZU_REGISTRY_PASSWORD
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $TKG_HARBOR_CA_LOCATION)

cartographer:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $TKG_HARBOR_CA_LOCATION)

supply_chain: basic

shared:
  ingress_domain: #@ data.values.INGRESS_DOMAIN

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.HARBOR_REGISTRY_HOST
    repository: #@ data.values.HARBOR_PROJECT
    ca_cert_data: |
$(awk '{printf "      %s\n", $0}' < $TKG_HARBOR_CA_LOCATION)

  gitops:
    ssh_secret: ""

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  app_config:
    app:
      baseUrl: #@ "http://tap-gui." + data.values.INGRESS_DOMAIN
    backend:
      baseUrl: #@ "http://tap-gui." + data.values.INGRESS_DOMAIN
      cors:
        origin: #@ "http://tap-gui." + data.values.INGRESS_DOMAIN
    catalog:
      locations:
        - type: url
          target: #@ data.values.CATALOG_URL

metadata_store:
  ingress_enabled: true
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP

scanning:
  metadataStore:
    url: ""

grype:
  namespace: "tap-install"
  targetImagePullSecret: "tap-registry"

learningcenter:
  ingressDomain: #@ "learning." + data.values.INGRESS_DOMAIN
  imageRegistry:
    username: #@ data.values.HARBOR_REGISTRY_USERNAME
    password: #@ data.values.HARBOR_REGISTRY_PASSWORD
    host: #@ data.values.HARBOR_REGISTRY_HOST

cnrs:
  domain_name: #@ data.values.INGRESS_DOMAIN

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  samples:
    include: true

source_controller:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $TKG_HARBOR_CA_LOCATION)

