#@ load("@ytt:data", "data")
---

profile: #@ data.values.PROFILE

excluded_packages:
- policy.apps.tanzu.vmware.com

shared:
  ingress_domain: #@ data.values.INGRESS_DOMAIN
  image_registry:
    project_path: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
    username: #@ data.values.INTERNAL_REGISTRY_USERNAME
    password: #@ data.values.INTERNAL_REGISTRY_PASSWORD
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $REGISTRY_CA_CERT_PATH)

ceip_policy_disclosed: true

buildservice:
  kp_default_repository: #@ data.values.INTERNAL_REGISTRY_HOST + "/" + data.values.INTERNAL_PROJECT + "/" + data.values.INTERNAL_REPOSITORY
  kp_default_repository_username: #@ data.values.INTERNAL_REGISTRY_USERNAME
  kp_default_repository_password: #@ data.values.INTERNAL_REGISTRY_PASSWORD

cartographer:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $REGISTRY_CA_CERT_PATH)

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.INTERNAL_REGISTRY_HOST
    repository: #@ data.values.INTERNAL_SUPPLY_CHAIN_PROJECT
  gitops:
    ssh_secret: #@ data.values.GITOPS_SSH_SECRET_NAME

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  app_config:
    catalog:
      locations:
        - type: url
          target: #@ data.values.CATALOG_URL

metadata_store:
  ingress_enabled: true
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP

scanning:
  metadataStore:
    url: ""

grype:
  namespace: #@ data.values.INSTALL_NAMESPACE
  targetImagePullSecret: #@ data.values.REGISTRY_SECRET_NAME

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  ingress:
    include: true
    enable_tls: false
  samples:
    include: true

appliveview:
  ingressEnabled: true

appliveview_connector:
  backend:
    ingressEnabled: true
    sslDeactivated: false

source_controller:
  ca_cert_data: |
$(awk '{printf "    %s\n", $0}' < $REGISTRY_CA_CERT_PATH)
